runtime: java17

runtime_config:
  operating_system: "ubuntu22"

entrypoint: java -jar rest-webservice-1.0.0-SNAPSHOT.jar

handlers:
  - url: /static
    static_dir: static

manual_scaling:
  instances: 1