workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - test
  - build & push

variables:
  JSON_KEY: $KEY
  ACCOUNT: $SA

image: samybacha/gcloud-maven

test:
  stage: test
  script:
    - mvn test

build_push:
  stage: build & push
  before_script:
    - gcloud auth activate-service-account $ACCOUNT --key-file=$JSON_KEY
    - gcloud components install docker-credential-gcr
    - gcloud auth configure-docker eu.gcr.io
  script:
    - mvn clean install -DskipTests